### ISSUE TITLE
Whitespace in path not supported

### ISSUE THREAD

**Issue by deppli01** [Samuel-Phillips/pathtrunc#1]
Thanks for contributing a fun PATH filter. Enjoying using it.
A small problem though, whitespace in PATH is not supported.

    ~/tmp> mkdir 'foo bar'
    ~/tmp> cd 'foo bar'   
    usage: pathtrunc.py [-h] path len
    pathtrunc.py: error: argument len: invalid int value: 'bar'

Resolved with patch.

```
if __name__ == '__main__':
     parser = argparse.ArgumentParser()
-    parser.add_argument('path')
+    parser.add_argument('path', nargs='+')
     parser.add_argument('len', type=int)
 
     args = parser.parse_args()
-
-    path = args.path
+    path = ' '.join(args.path)
     home = os.getenv('HOME')
     if home:
         if home.endswith('/'):
```

**Comment by sp5** [comment]
1. Please show me the code where you're calling pathtrunc
2. What shell are you using?

**Comment by deppli01** [comment]
>  1. Please show me the code where you're calling pathtrunc
PS1="${HOSTNAME}:\$(~/bin/pathtrunc.py \$PWD 25)> "

>  2. What shell are you using?
Gentoo Linux, with
app-shells/ksh-2020.0.0-r1 (/bin/ksh)
app-shells/bash-5.1_p4 (/bin/bash)

If PS1 is set with $PWD quoted, pathtrunc.py issue is hidden:
export PS1="${HOSTNAME}:\$(~/bin/pathtrunc.py% \"\$PWD\" 25)> "

But IMHO, it would be more friendly if parsing was not whitespace sensitive.
Though, would probably need to formalize, provide parameter switches for the path length, and move the path parameter to the end.
Maybe more hassle than worth.  :)

**Comment by sp5** [comment]
This is normal shell behavior, you'll see the same thing anywhere you use unquoted variables in a POSIX-compatible shell. Bash documents it here: https://www.gnu.org/software/bash/manual/html_node/Word-Splitting.html
